version: '3.4'

services:

  nginx.admin:
    image: nginx

  nginx.shop:
    image: nginx

  rabbitmq:
    image: rabbitmq:3-management

  catalogdb:
    image: mongo

  admindb:
    image: postgres

  basketdb:
    image: mongo


  admin.api:
    image: ${DOCKER_REGISTRY-}admin.api
    build:
      context: .
      dockerfile: Services/Admin/Admin.API/Dockerfile
  


  adminwebapp:
    image: ${DOCKER_REGISTRY-}adminwebapp
    build:
      context: .
      dockerfile: WebApps/Admin/AdminWebApp/Dockerfile


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalog.worker:
    image: ${DOCKER_REGISTRY-}catalogworker
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Worker/Dockerfile

  shopwebapp:
    image: ${DOCKER_REGISTRY-}shopwebapp
    build:
      context: .
      dockerfile: WebApps/Shop/ShopWebApp/Dockerfile

  authdb:
    image: mcr.microsoft.com/mssql/server


  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  basket.worker:
    image: ${DOCKER_REGISTRY-}basketworker
    build:
      context: .
      dockerfile: Services/Basket/Basket.Worker/Dockerfile

volumes:
  postgres_data:
  mongo_data:
  basket_data:

