version: '3.4'

services:
  admindb:
    container_name: admindb
    environment: 
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=AdminDb
    restart: always
    ports: 
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  admin.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
