version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management

  catalogdb:
    image: mongo

  admindb:
    image: postgres

  admin.api:
    image: ${DOCKER_REGISTRY-}admin.api
    build:
      context: .
      dockerfile: Services/Admin/Admin.API/Dockerfile
  


  adminwebapp:
    image: ${DOCKER_REGISTRY-}adminwebapp
    build:
      context: .
      dockerfile: WebApps/Admin/AdminWebApp/Dockerfile


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalog.worker:
    image: ${DOCKER_REGISTRY-}catalogworker
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Worker/Dockerfile

volumes:
  postgres_data:
  mongo_data:




