version: '3.4'

services:

  nginx:
    volumes:
      - ./Nginx/Admin/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1337:80"
    depends_on:
      - admin.api

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=shop
      - RABBITMQ_DEFAULT_PASS=s123456
      - RABBITMQ_DEFAULT_VHOST=/

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  admindb:
    container_name: admindb
    environment: 
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=AdminDb
    restart: always
    ports: 
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  identitydb:
   container_name: identitydb
   user: root
   environment:
     - SA_PASSWORD=password
     - ACCEPT_EULA=Y
   restart: always
   ports:
     - '1434:1433'

  admin.api:
    container_name: admin.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=shop
      - RABBITMQ_PASSWORD=s123456
    ports:
      - "8000:80"

  adminwebapp:
    container_name: adminwebapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://admin.api"
    depends_on:
    - admin.api
    ports:
      - "5000:80"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    depends_on:
      - catalogdb

  catalog.worker:
    container_name: catalog.worker
    environment:
      - MONGO_CONNECTION_STRING=mongodb://catalogdb:27017
      - MONGO_DATABASE=catalogdb
      - MONGO_COLLECTION=Catalog
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=shop
      - RABBITMQ_PASSWORD=s123456
  shopwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"


  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ConnectionStrings:AuthConnectionString=Server=identityserverdb;Database=IdentityServerDb;User Id=sa;Password=password'
    ports:
      - "80"

