version: '3.4'

services:

  nginx.admin:
    container_name: nginx.admin
    volumes:
      - ./Nginx/Admin/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1337:81"
    depends_on:
      - admin.api

  nginx.shop:
    container_name: nginx.shop
    volumes:
      - ./Nginx/Shop/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1338:80"
    depends_on:
      - catalog.api

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=shop
      - RABBITMQ_DEFAULT_PASS=s123456
      - RABBITMQ_DEFAULT_VHOST=/

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  admindb:
    container_name: admindb
    environment: 
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=AdminDb
    restart: always
    ports: 
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  admin.api:
    container_name: admin.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=shop
      - RABBITMQ_PASSWORD=s123456
    ports:
      - "8000:80"

  adminwebapp:
    container_name: adminwebapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://admin.api"
      - "ApiSettings:IdentityAddress=https://identity.api"
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      #- "5004:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    depends_on:
      - catalogdb

  catalog.worker:
    container_name: catalog.worker
    environment:
      - MONGO_CONNECTION_STRING=mongodb://catalogdb:27017
      - MONGO_DATABASE=catalogdb
      - MONGO_COLLECTION=Catalog
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=shop
      - RABBITMQ_PASSWORD=s123456

  shopwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"


  identitydb:
    container_name: identitydb
    user: root
    environment:
      - SA_PASSWORD=Vonyuchka_Ne_Stavitsya!!1609!!
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - '1434:1433'


  #identity.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    #- ASPNETCORE_URLS=https://+:443;http://+:80
  #    - 'ConnectionStrings:AuthConnectionString=Server=tcp:identitydb;Database=IdentityDb;User Id=sa;Password=Vonyuchka_Ne_Stavitsya!!1609!!'
  #  ports:
  #    - "5002:80"
  #  #  - "5003:443"
  #  #volumes:
  #  #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #  #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8005:80"

